export { default as logo } from "./images/reflect-logo.jpg"
export { default as banner } from "./images/banner.jpg"
export { default as solgrow_banner } from "./images/solgrow-banner.jpg"
export { default as solgrow } from "./images/solgrow.png"
export { default as mobileBanner } from "./images/mobile-banner.png"